### ISSUE TITLE
invalid transactions on new OUI initialization

### ISSUE THREAD

**Issue by lthiery** [helium/router#233]
When setting up an OUI, we had repeated "bad_nonce" error from Router, which was trying to write a filter and open multiple state channels (oddly with 45 and 90 block expirations, depsite `.env-router` being set for 45).

Logs here

[router.log](https://github.com/helium/router/files/6086714/router.log)

It seems like on boot, filter write and SCs are spammed and mutually invalidating each other (nonce collisions?).

We tried rolling back a few Router versions, to no avail. Finally, we set `ROUTER_XOR_FILTER_WORKER=false` and restarted which appeared to make the state channels work okay.

**Comment by macpie** [comment]
The 2 state channels will have different expiration date so that they can overlap. 

There should not be any collision in between the 2 nonces  as they are different.

After talk with Louis seems like the chain was having issue which can cause so "funky"  behavior for the state channels. 

Will close the issue for now as we already have the other state channels issue reported here https://github.com/helium/router/issues/223
