### ISSUE TITLE
2 values sent at same time

### ISSUE THREAD

**Issue by simonsaysjake** [helium/router#347]
Following the system wide outage today, upon coming online, device sent 2 pings at exact same time - aka the router had them in a queue then sent them at the same time. This means 2 values sent to our platform at the same time. The timestamps therefore are not true. Timestamps must remain true for Helium to be trusted with data.
<img width="1063" alt="Screen Shot 2021-06-23 at 3 10 52 PM" src="https://user-images.githubusercontent.com/12376742/123155000-8da9c200-d435-11eb-8e83-939eff3f4550.png">

**Comment by macpie** [comment]
Router does not queue uplinks, the hotspots do (when it cannot reach Router). For trust reasons, we cannot mark the timestamp on the hotspot so the timestamp is marked upon reception in Router. This is why, you see this behavior of 2 packets coming one after the other with very close timestamps.

To avoid this potential issue we added the field `hold_time` [see here](https://github.com/helium/router#integrations-data). This field will tell you how long the hotspot was holding the uplink so that users can make a decision on whether to keep the data that could still be valuable or discard it.

**Comment by jdgemm** [comment]
Here's more information about `hold_time` [here](https://github.com/helium/router/issues/347#issuecomment-867191978). Also, the way to ensure you're getting the most accurate sensor timestamps is to have the sensors themselves send timestamp information.
