### ISSUE TITLE
Support Long Range-Frequency Hopping Spread Spectrum (LR-FHSS) channels 

### ISSUE THREAD

**Issue by mikev** [helium/router#807]
In January 2022, SemTech introduced a new channel DataRate known as Long Range-Frequency Hopping Spread Spectrum (LR-FHSS).  This DataRate's primary use case is satellite Uplinks, however LR-FHSS does have many benefits beyond satellites.  The primary benefit is that it increases total Network Capacity by an order of magnitude.

List of Benefits:
- Satellite Uplinks
- Enhanced deep indoor capacity
- Supports any regional dwell time limitations
- Enabling more transmission power
- Maximized capacity for spectrum constrained regions

Helium's network would benefit if LR-FHSS is implemented and supported.  Given that the feature simply requires a firmware upgrade to SX1302 SemTech chips it should be possible to upgrade and support existing Hotspots, provided Helium code to support the new DataRate is also implemented.

A theoretical description of LR-FHSS is here, in the paper LR-FHSS: Overview and Performance Analysis pending publication to IEEE.
https://arxiv.org/pdf/2010.00491.pdf

SemTech first announced the technology and intent to create LR-FHSS channels in Nov 2020.
https://blog.semtech.com/lorawan-protocol-expands-network-capacity-with-new-long-range-frequency-hopping-spread-spectrum-technology

Jan 2022, SemTech announced that LR-FHSS was available via a firmware upgrade to SX1302-based V2.1 gateways
https://www.businesswire.com/news/home/20220111005293/en/Semtech-Announces-New-Tool-Suite-Enabling-Dense-Deployments-and-Satellite-Connectivity-for-LoRa%C2%AE

On May 31, 2022 - TTN announced support for LR-FHSS in the v3.14 release
https://www.thethingsindustries.com/news/the-things-industries-expands-lorawan-network-capacity-by-supporting-lr-fhss-data-rates/

SemTech LR-FHSS end-point demo source code
https://github.com/Lora-net/SWDM001

**Comment by pdvaneijk** [comment]
Sorry, the above statement is not true: 

"Given that the feature simply requires a firmware upgrade to SX1302 SemTech chips it should be possible to upgrade and support existing Hotspots, provided Helium code to support the new DataRate is also implemented."

LR-FHSS requires a custom binary from Semtech to run on a Texas Instrument DSP (OMAP L138). Several years ago Semtech developed a gateway reference design that we called V2.1. This design muxes the I/Q data from the RF front end to both one or more SX130Xs as well as to this TI DSP. In LR-FHSS packets get broken up into 50-bit chuncks, and are encoded with a Viterbi convolutional code, whitened, etc. Each chunk is transmitted on a different pre-defined frequency. Hence the hopping. At the beginning of each packet 2 or 3 copies of the same header are sent on different channels. Each header contains a information that gives the receiver a heads up on what to hopping sequence of this upcoming packet will be, how many pieces etc so that the DSP can put the packet back together. Since there is parity built into the individual segments the receiver does not have to receive all the pieces of the packet in order to put it back together. The advantage of LR-FHSS over LoRaWAN is that a LR-FHSS capable gateway can process 100s and 100s of LR-FHSS packets at the same time. 

So right now LR-FHSS gateways required to use this TI-OMAP with a custom binary from Semtech. 

Initially LR-FHSS was known as LoRa-E, but since this has nothing to do with LoRa (we currently actually use GSMK, but could upgrade to a higher level modulation like QPSK). The idea was that LR-FHSS would benefit highly dense terrestrial sensor deployments like water meters. Now what we are seeing is that satellite providers are jumping on LR-FHSS. Echostar has just announced a solution where their Geo satellite above Europe is now able to receive LR-FHSS signals from terrestrial devices. The satellite itself does not speak LR-FHSS, but it will simply receive the LR-FHSS signal in the lower end of the S-band (around 2 Ghz) and then send the signal to one of its ground stations. A the ground station a LR-FHSS capable gateway will then process the LR-FHSS packet. Echostar has developed an RF module that speaks both LR-FHSS in the lower end of the S-band and LoRaWAN in SubGhz using the LR1120. One can now develop a tracker that will connect to a terrestrial network (like Helium) with LoRaWAN when available or to the Satellite using LR-FHSS when there is no terrestrial network.
